### ISSUE TITLE
Better ordering of directions?

### ISSUE THREAD

**Issue by kchonka** [recipe-ipsum/recipe-ipsum#24]
The way the recipe generating algorithm is currently set up, some steps appear before others in a way that doesn't make logical sense. 

Ex: "Transfer to a plate & serve immediately" can randomly appear before "Preheat the oven."

An improvement to this would be to possibly separate directions into groups? Directions that come first, directions that come in the middle, directions that come in the end? Just to make the end recipe more coherent/logically flowing.

**Comment by gabLaroche** [comment]
Yes I agree, I do want to keep this behaviour, because I find it quite funny sometimes, but this would fit perfectly in the "serious mode" PR: #13 commit: #11

**Comment by Brainshaker95** [comment]
I would like to work on this issue

**Comment by Brainshaker95** [comment]
@gabLaroche Did you notice the PR? #37

**Comment by gabLaroche** [comment]
@Brainshaker95 Yes I noticed, I'm very sorry, I was swamped at work, I'll take a look at the PR

**Comment by Brainshaker95** [comment]
@gabLaroche I'm kindly asking you to add the hacktoberfest-accepted label to my PR. If this is not something you want to to, please telle me so that I can use the remaining days to hunt for another repo to participate

**Comment by gabLaroche** [comment]
@Brainshaker95 Yes of course! it's my bad, I thought I had the hacktoberfest label on the project itself, apparently not haha
